### PR TITLE
chore: use toolchain for leanprover/lean4#2749

### PR DESCRIPTION
**Pull request by semorrison**
* Lean 4 PR: leanprover/lean4#2749
* Mathlib bump that we need to get working, currently failing with a ProofWidgets error: https://github.com/leanprover-community/mathlib4/pull/8216

### CODE REVIEW

**Comment by semorrison** [comment]
This is broken, and needs fixing! @tydeu, @Vtec234, would one of you be able to sort this out?

**Comment by Vtec234** [comment]
Ah, this isn't an issue caused by the bump; the Mac CI just deadlocks nondeterministically. I have observed this before. It may be due to the mutex [here](https://github.com/leanprover-community/ProofWidgets4/blob/f1a5c7808b001305ba07d8626f45ee054282f589/lakefile.lean#L47), but I don't know of another way to achieve what the lakefile does.

**Comment by semorrison** [comment]
> Ah, this isn't an issue caused by the bump; the macOS CI just deadlocks nondeterministically. I have observed this before. It may be due to the mutex [here](https://github.com/leanprover-community/ProofWidgets4/blob/f1a5c7808b001305ba07d8626f45ee054282f589/lakefile.lean#L47), but I don't know of another way to achieve what the lakefile does.

Ah, I think I've noticed this locally as well!

**Comment by semorrison** [comment]
Okay, separately from sorting out the CI failure here, the point is that https://github.com/leanprover-community/mathlib4/pull/8216 is currently failing when trying to compile Mathlib on the toolchain from https://github.com/leanprover/lean4/pull/2749, and the failure is from ProofWidgets!

**Comment by Vtec234** [comment]
> Okay, separately from sorting out the CI failure here, the point is that [leanprover-community/mathlib4#8216](https://github.com/leanprover-community/mathlib4/pull/8216) is currently failing when trying to compile Mathlib on the toolchain from [leanprover/lean4#2749](https://github.com/leanprover/lean4/pull/2749), and the failure is from ProofWidgets!

I see, I think it's because that PR points at the `lean-pr-testing-2749` branch which does not have an associated cloud release. Note that even if the build here succeeded, the mathlib build would still fail since we do not upload cloud releases for PRs, only for tagged commits. If you just point mathlib back at the latest release (v0.0.21), I think the build should succeed.

**Comment by Vtec234** [comment]
Ah, no, am I reading correctly that it also failed while pointed at `v0.0.21`? It does look like a cloud release failure in any case, implying that somehow the release archive was not downloaded correctly.

**Comment by tydeu** [comment]
@Vtec234 The underlying compatibility issue with the PR is that the ProofWidgets hard-codes references to `build` directory in its code (see below) and its default location changes in the PR.

https://github.com/leanprover-community/ProofWidgets4/blob/f1a5c7808b001305ba07d8626f45ee054282f589/ProofWidgets/Compat.lean#L174

A forward-compatible fix would be to manually set `buildDir := "build"` in the `lakefile.lean` package configuration rather than relying on the changing default.

**Comment by semorrison** [comment]
Shouldn't it be the other way? That `Compat.lean` should use the build dir?

As long as it will work downstream in Mathlib I don't really mind!

**Comment by tydeu** [comment]
@semorrison True, one solution is to change the hard-coded value to the new default. However, I think setting `buildDir` to an explicit value (or, alternatively, outputting the JS to a specific unique directory e.g. `dist`) is a good idea because ProofWidgets is relying on the JS being in a specific place for its correctness. It avoids any repeat of this problem should any further reorganization happen in the future (which could be in the cards).

**Comment by semorrison** [comment]
Oh, I meant that `Compat.lean` should *ask* where the build dir is!

**Comment by semorrison** [comment]
Hmm... my reaction to all of this is that we should not provide any ability to customize the build directory, if providing customization leaves us in this situation! But that is not a discussion for this PR.

@Vtec234, are you happy with `buildDir := "build"`?

**Comment by tydeu** [comment]
@Vtec234 Or `buildDir := "dist"` if you want to be more JS-like. 😉

**Comment by Vtec234** [comment]
`buildDir := "build"` is okay. Let's try it here.

**Comment by Vtec234** [comment]
I made a release, `v0.0.22-pre`, which you can point to in the mathlib PR.

**Comment by semorrison** [comment]
Okay, I have updated https://github.com/leanprover-community/mathlib4/pull/8216 to use the pre-release.

**Comment by tydeu** [comment]
@Vtec234 Since this is a backwards- and forwards-compatible fix, it seems like it can be merged independently of the upstream PR. What do you think?

**Comment by Vtec234** [comment]
For sure. I made that change on `main` and released `v0.0.22`. Does the existence of both releases imply we can close this?

**Pull request closed without merging**
