### PR TITLE
feat: title of filter button depending on state

### PR DESCRIPTION
**Pull request by JovanGerb**

### CODE REVIEW

**Comment by Vtec234** [comment]
About the filter icon (see #50),

> In my use case, you can see immediately whether you are in the filtered or unfiltered state because in the unfiltered case you can see the lemma names and in the filtered case not. So clicking never appears to do nothing.

Are there no situations in which the filtered and unfiltered states are the same?

**Comment by JovanGerb** [comment]
> About the filter icon (see #50),
> 
> > In my use case, you can see immediately whether you are in the filtered or unfiltered state because in the unfiltered case you can see the lemma names and in the filtered case not. So clicking never appears to do nothing.
> 
> Are there no situations in which the filtered and unfiltered states are the same?

The only scenario in which the states are the same is if both are `<p> No rewrites found for <InteractiveCode fmt={← ppExprTagged e}/> </p>`

**Comment by JovanGerb** [comment]
Now that I think of it, if both the filtered and unfiltered case have no results, there is no reason to use the filter button anyways. If I change that, then the two states will never be the same.

**Comment by Vtec234** [comment]
For now I will err on the side of consistency and claim that the filter button will cease to be distracting after a day or so of usage where it is filled-in reflecting the UI state. But if you are still bothered by it after such an experiment, feel free to make another PR and I will merge it.

**Pull request merged**
